export const metadata = {
  title: "Municipalidad de Sacanta",
  description: "Generated by Next.js",
};
import "../styles/globals.css";
import { Navigation } from "./components/Navigation";

// funcionan como routes todas las carpetas que tengan
// el archivo page.jsx en su carpeta, sino no son routes

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Web Institucional</title>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
